language: ruby
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database kpdotcom_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:schema:load
